[FEAT] Auth 도메인 API mocking
TEAM-YOAJUNG/backend-server pull request #22
Opened 2024-10-23 16:32 UTC by jungyuminn

## 1. 관련 이슈

#21 

## 2. 구현한 내용 또는 수정한 내용

1. 로그인 기능
2. 회원가입 기능
3. 이메일 인증코드 발송 기능
4. 비밀번호 변경 기능
5. 비밀번호 찾기(재발급) 기능
6. 로그아웃 기능
7. 회원탈퇴 기능

## 3. TODO

## 4. 배포 전 Checklist

2024-10-24 02:14 UTC, EeeasyCode requested changes
구현하느라 고생 많으셨습니다! 코멘트 확인 후 수정사항 발생하면 말씀해주세요!

+ 추가적으로 현재 JWT 관련된 논리적인 흐름을 코멘트로 달아주시면 좋을 것 같습니다~~!

2024-10-24 07:20 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +    private UserService userService;
해당 구조로 authcontroller 수정했습니다.

2024-10-24 08:22 UTC, opp-13 commented on auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
> +            @Parameter(description = "회원가입 정보") @Valid @RequestBody RegistrationDto registrationDto);
auth-service/src/main/java/club/gach_dong/entity/User.java에서 속성을 String으로 설정하셨는데 이 경우 JPA로 처리 시 VARCHAR(255)로 선언됩니다. 255자 이상 넘어가는 입력에 대해서는 예외 처리하는 것이 좋지 않을까요?

2024-10-24 11:00 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
> +            @Parameter(description = "회원가입 정보") @Valid @RequestBody RegistrationDto registrationDto);
user entity에 예외 처리 추가하였고, RegistrationDto에도 더 자세하게 valid 추가하였습니다.

2024-10-24 11:11 UTC, opp-13 commented on auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
> +            @Parameter(description = "회원가입 정보") @Valid @RequestBody RegistrationDto registrationDto);
고생하셨습니다!!!!!

2024-10-24 12:39 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +
토큰 관련 유틸 함수들 모듈화하였습니다.

2024-10-24 16:19 UTC, EeeasyCode commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +
고생하셨습니다!

2024-10-24 22:49 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/entity/User.java
> +@Table(name = "users")
기존 코드 정적 팩토리 메소드로 변경했습니다. UserService의 객체 생성 부분도 반영해서 수정하였습니다. AuthController에도 해당 내용에 맞게 수정하였습니다.

2024-10-25 13:50 UTC, EeeasyCode commented on auth-service/src/main/resources/application.yml
> +spring:
@jungyuminn 
혹시 이 부분 수정되었을까요~?

2024-10-25 23:46 UTC, jungyuminn commented on auth-service/src/main/resources/application.yml
> +spring:
> @jungyuminn 혹시 이 부분 수정되었을까요~?

수정 완료했습니다

2024-10-26 03:17 UTC, opp-13 approved these changes
수정하시느라 고생 많으셨습니다!

2024-10-26 11:38 UTC, opp-13 commented on auth-service/src/main/java/club/gach_dong/util/JwtUtil.java
> +        redisTemplate.opsForValue().set(token, "blacklisted", 30, TimeUnit.MINUTES);
유효기간이 1일인 토큰을 30분간 blackList 처리 하는 것보다는 1일 간 blackList 처리하거나 아니면 JWT 토큰의 남은 유효기간 동안 blackList 처리 하는 게 낫지 않을까요?
Ex)
<pre>
<code>
        Claims claims = Jwts.parser()
                .setSigningKey(secret_key)
                .parseClaimsJws(accessToken)
                .getBody();

        Date expirationDate = claims.getExpiration();
        Date currentDate = new Date();
        long differenceInMilliseconds = expirationDate.getTime() - currentDate.getTime(); // 이 값을 만료 시간으로 설정합니다.
</code>
</pre>

2024-10-26 15:50 UTC, EeeasyCode commented
@jungyuminn 
유민님, 혹시 마무리 작업 끝난 PR일까요?? 이상 없으시면 merge 진행하고 api-gateway 연결 작업이랑 배포 작업을 진행해야 해서요!
우선, API Spec 이 swagger로 나와야하는게 우선이라 큰 문제없다면 말씀해주세요!

2024-10-26 17:49 UTC, jungyuminn commented
@EeeasyCode 
아까 계속 확인하고 했었는데, 빠진게 계속 나와서 수정하고 추가했습니다. 지금 최종 api 테스트까지 다 진행해서 마무리했습니다.

2024-10-26 17:58 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/util/JwtUtil.java
> +        redisTemplate.opsForValue().set(token, "blacklisted", 30, TimeUnit.MINUTES);
계속 테스트하느라 기존에 30분으로 나뒀었습니다. 근데 1일동안 블랙리스트 처리하려고 했는데, 남은 유효 기간으로 하는 게 더 나아보이네요! 반영해서 수정했습니다!

2024-10-27 11:30 UTC, EeeasyCode commented
@jungyuminn 그럼 merge 진행해도 괜찮을까요?!

2024-10-27 11:40 UTC, EeeasyCode approved these changes
고생 많으셨어요~~

2024-10-27 16:38 UTC, merged