feat: 인증코드 검증 및 회원정보 조회 api 추가
TEAM-YOAJUNG/backend-server pull request #47
Opened 2024-10-31 21:14 UTC by jungyuminn

## 1. 관련 이슈

#46 

## 2. 구현한 내용 또는 수정한 내용

- 회원가입 api 수정
- 인증코드 검증 api 생성
- 회원정보 조회 api 생성

+ 창민님이 PublicApiSpecification에 import문 추가해주신 부분을 이전 PR에서 실수로 재누락했습니다. 이 부분 다시 추가하였습니다 

## 3. TODO

## 4. 배포 전 Checklist
@EeeasyCode

2024-10-31 21:20 UTC, jungyuminn commented
@kangju2000 

회원정보 조회 api는 사용자의 email, name, role 만을 반환하며,
인증코드 검증 api는 email과 code를 요청하는데, Redis에 저장된 인증 코드는 이메일을 키로 사용하여 관리되므로, 이메일이 필수적으로 필요합니다. 일단 회원가입 api에서 인증코드를 받는 부분은 제거했고, 인증코드 검증 api에서 code만 받을 수 있도록 방법이 있는지 더 찾아보겠습니다.

2024-11-01 07:55 UTC, EeeasyCode requested changes
고생하셨습니다~ 리뷰 남겼고, 해당 PR은 제가 올린 PR merge된 이후 순차적으로 merge되면 될 것 같습니다.

2024-11-01 07:55 UTC, EeeasyCode commented on auth-service/src/main/java/club/gach_dong/dto/UserProfileDto.java
> +public class UserProfileDto {
Request나 Response에 쓰이는 DTO 객체인 경우에 저희 내부에서 사용중인 DTO 컨벤션에 맞춰 변경해주세요!

2024-11-01 07:55 UTC, EeeasyCode commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +
객체 생성 부분도 클래스 내부에서 정적 메서드로 처리하면 보기 좋을 것 같아요~!

2024-11-01 14:18 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/dto/UserProfileDto.java
> +public class UserProfileDto {
response/request에 따라 분류했고 컨벤션 맞춰서 수정했습니다.

2024-11-01 14:22 UTC, jungyuminn commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +
혹시 userservice에서 객체 생성 시 정적메소드를 사용하고 controller에서 호출하고 있는데, controller 내부에서 생성하는 게 더 나을까요? 너무 분산될 것 같아서요

2024-11-01 14:30 UTC, EeeasyCode reviewed
고생하셨습니다~ 리뷰 남겼고, 해당 PR은 제가 올린 PR merge된 이후 순차적으로 merge되면 될 것 같습니다.

2024-11-01 14:30 UTC, EeeasyCode commented on auth-service/src/main/java/club/gach_dong/controller/AuthController.java
> +
음.. 정확하게 어떤 부분을 말씀하시는지 잘 모르겠어서 제가 이해한대로 설명을 해볼게요!

1. userservice에서 객체 생성 시 정적메소드를 사용하고 controller에서 호출한다.
-> User Entity 생성 시, User Service에서 생성한다. 로 이해가 되는데 이 부분은 Service에서 수행되어야 하는게 맞는 것 같아요.
Service 자체가 비즈니스 로직이 존재해야하는 부분이고, Domain의 Entity 조작 책임은 Service가 갖고 있는거라서요!

2. controller 내부에서 생성한다.
-> 1번 답변과 동일하게, controller에서는 service에서 생성된 entity 객체를 받아오는 게 맞습니다! 또한, response에 대한 객체는 controller 영역에서 책임이 있는거라 response/request 객체 생성은 controller에서 수행되는거구요.

2024-11-01 15:51 UTC, EeeasyCode approved these changes
@jungyuminn 
기능 추가 이후에 문제 없으시면, PR 직접 merge해주세요~~

2024-11-01 19:22 UTC, merged