[FEAT] 프로필 이미지 관련 기능 추가
TEAM-YOAJUNG/backend-server pull request #49
Opened 2024-11-02 11:33 UTC by jungyuminn

## 1. 관련 이슈

#35 

## 2. 구현한 내용 또는 수정한 내용

- [x] 프로필 이미지 업로드
- [x] 프로필 이미지 조회
- [x] 프로필 이미지 수정
- [x] 프로필 이미지 삭제

## 3. TODO

## 4. 배포 전 Checklist
@EeeasyCode

2024-11-02 14:27 UTC, opp-13 commented on user-service/src/main/resources/application.yaml
기본 설정은 MultipartFile 형식의 단일 파일 기준 1MB까지 업로드가 가능해서 파일 사이즈를 5MB까지 허용하시려면 여기서 추가적인 설정이 필요하실 것 같습니다! 
EX)
<pre>
<code>
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
</code>
</pre>

2024-11-02 15:07 UTC, jungyuminn commented on user-service/src/main/resources/application.yaml
로컬은 넣었었는데 누락된 것 같습니다. 수정해서 반영했습니다 감사합니다!

2024-11-03 16:08 UTC, EeeasyCode requested changes
고생하셨습니다! 리뷰 확인부탁드려요~

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/api/UserApiSpecification.java
> +
아! 이거 auth쪽도 동일한 이야기인데, URI path에 underbar(_) 사용은 지양해주세요!
[RestAPI 에서 제안하는 것](https://restfulapi.net/resource-naming/) 중 하나가 seo를 위한 설계에서 underbar는 사용하는 것을 지양하고 있다고 해요!
해당 부분 수정에 대한 branch를 fix로 구성해서 PR 올려주시면 감사할 것 같습니다!

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/config/S3Config.java
> +
혹시 Object Storage를 S3로 사용하신 이유가 있을까요??
@opp-13 성호님 파일 업로드 부분은 GCP Object Storage로 구성되어 있는 것 같아서요!

그리고, 해당 secret 값에 대한 내용 전달해주시면 될 것 같습니다.

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/config/SwaggerConfig.java
> +
``` java
private Components component() {
        return new Components()
                .addSecuritySchemes("Authorization",
                        new SecurityScheme()
                                .type(SecurityScheme.Type.HTTP)
                                .scheme("Bearer")
                                .bearerFormat("JWT"));
    }
```
    가 추가되면 좋을 것 같습니다!

그리고, 

```java
private Components defaultJsonResponse() {
        ApiResponse jsonResponse = new ApiResponse()
                .description("Default JSON response")
                .content(new Content()
                        .addMediaType("application/json", new MediaType()));

        return new Components().addResponses("defaultJsonResponse", jsonResponse);
    }
``` 
해당 코드는 지워주시고, application-dev.yaml에
```yaml
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
``` 
이 추가되면 될 것 같습니다!

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +            User user = userRepository.findByEmail(userId)
컨트롤러에서 UserRepository 객체에 접근하는 로직이 존재하는 이유에 대해서 알 수 있을까요?
그리고, findByEmail -> 매개변수는 userId로 넘겨지고 있는데, 확인 부탁드립니다.

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +                    });
이 부분도 위와 같이, 도메인 객체 생성에 대한 로직이 service가 아닌 controller에 존재하는 이유가 궁금합니다.

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
> +
Response와 Request에 Optional인지 아닌지 확실하게 명시되면 좋을 것 같아요.
가령, response data field 중 Null로 return 될 수 없는 Type은 @NotNull 과 같은 명시가 필요해요!

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/entity/User.java
> +public class User {
User Entity의 전체 필드는 email과 profileImage가 전부인거죠?
그 때, 논의했던 auth - user 간 식별자나 추가적인 데이터는 필요하지 않는 건가요?

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/service/UserService.java
> +
확장자 검증을 화이트 리스트 기반으로 utli이나 내부 메서드로 등록해 사용하면 더 좋을 것 같아요!

```java
import java.util.Set;

public class ImageUploadValidator {

    private static final Set<String> ALLOWED_CONTENT_TYPES = Set.of("image/png", "image/jpeg", "image/jpg");

    public void validateContentType(String contentType) {
        if (!ALLOWED_CONTENT_TYPES.contains(contentType)) {
            throw new IllegalArgumentException("허용되지 않는 이미지 형식입니다. PNG, JPG, JPEG 파일만 업로드 가능합니다.");
        }
    }
}
```

2024-11-03 16:08 UTC, EeeasyCode commented on user-service/src/main/resources/application.yaml
> +
저희는 지금 한 가지 클라우드 provider를 사용중인 환경이 아니라서, 이런 key 같은 경우
aws-access-key 처럼 확실하게 구분해주시면 좋을 것 같아요!

2024-11-03 16:24 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/config/S3Config.java
> +
저는 aws 사용하려고 했는데 아까 문제가 생겨서 gcp로 바꿔야할 것 같습니다.

2024-11-03 16:26 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/entity/User.java
> +public class User {
사용자가 로그인하면 gateway의 filter에 의해 헤더에 올라가있는 userId(email)을 가져오게 했습니다.
user-service에서 제가 담당한 부분이 프로필 이미지 관련 부분밖에 없어서 일단 필드를 email과 profileImage로 설정했습니다.

2024-11-03 16:38 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/config/SwaggerConfig.java
> +
수정했습니다!

2024-11-03 17:06 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +            User user = userRepository.findByEmail(userId)
해당 부분 service로 넘겼습니다. 그리고
```
String userId = httpServletRequest.getHeader("X-MEMBER-ID");

        if (userId == null || userId.isEmpty()) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(null);
        }

        try {
            User user = userService.getOrCreateUser(userId);

```
이 부분은 x-member-id에서 가져오는 userId를 의미해서 그렇게 사용했었습니다. 헤더에서 가져오는 실제 이메일이기 때문입니다.

2024-11-03 17:08 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +                    });
위 리뷰에서 같이 수정했습니다!

2024-11-03 17:09 UTC, jungyuminn commented on user-service/src/main/resources/application.yaml
> +
gcp로 변경하면서 수정하겠습니다.

2024-11-03 17:29 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
> +
수정했습니다!

2024-11-03 17:52 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/service/UserService.java
> +
수정했습니다!

2024-11-03 20:28 UTC, jungyuminn commented on user-service/src/main/resources/application.yaml
> +
수정완료했습니다.

2024-11-03 20:28 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/config/S3Config.java
> +
aws -> gcp로 수정완료했습니다.

2024-11-03 20:35 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/api/UserApiSpecification.java
> +
수정했습니다. auth도 fix로 branch 만들고 PR 올리겠습니다.

2024-11-04 06:34 UTC, EeeasyCode approved these changes
고생하셨습니다~! merge 해주세요!

2024-11-04 06:36 UTC, merged

2024-11-04 09:04 UTC, EeeasyCode commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +            User user = userRepository.findByEmail(userId)
@jungyuminn 
근데, 이 부분 저희가 저번에 이야기 나눴던 걸로는 email이 아닌, user-auth가 공통으로 가지고 있는 uuid로 설정하기로 하지 않았나요?

2024-11-05 00:06 UTC, jungyuminn commented on user-service/src/main/java/club/gach_dong/controller/UserController.java
> +            User user = userRepository.findByEmail(userId)
맞습니다. 근데 아직 userId를 uuid로 수정을 안했습니다. 지금 auth-service에 user, admin 테이블 분리 및 /admin 프리픽스 추가 작업 중에 있는데, 오늘 해당 작업이 끝나면 uuid까지 hotfix branch로 같이 올리겠습니다.